pipeline {
    agent any

    tools {
        maven 'Maven3'  // Ensure Maven is configured in Jenkins under Global Tool Config
        jdk 'JDK17'     // Ensure JDK is configured in Jenkins under Global Tool Config
    }

    environment {
        // You can specify other environment variables here if necessary
    }

    stages {
        stage('Checkout') {
            steps {
                // Use Git credentials for accessing the repository
                git credentialsId: 'github-ssh-key', url: 'git@github.com:rafiimafif/Project2.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('SonarQube Analysis') {
            environment {
                SONAR_TOKEN = credentials('sonarqube-token') // Replace with your Jenkins credential ID
            }
            steps {
                sh '''
                mvn sonar:sonar \
                  -Dsonar.projectKey=Project2 \
                  -Dsonar.host.url=http://your-sonarqube-url \
                  -Dsonar.login=$SONAR_TOKEN
                '''
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}
